### ISSUE TITLE
Firebase.Query problems

### ISSUE THREAD

**Issue by dahart** [isabo/firebase-externs#2]
Hi isabo, I grabbed your firebase-externs today and its working well, thank you! But I bumped into a minor issue with the Firebase.Query externs... I think the Query methods might be intended to be synonymous with the Firebase class, rather than separate? I'm not sure, and if I patch it up and get it working, I'll send a pull request. In the mean time, I boiled it down to a simple example. If you compile the limitToLast() example from the firebase docs, you'll get a warning.

https://www.firebase.com/docs/web/guide/retrieving-data.html#section-queries

var ref = new Firebase("https://dinosaur-facts.firebaseio.com/dinosaurs");
ref.orderByChild("weight").limitToLast(2).on("child_added", function(snapshot) {
  console.log(snapshot.key());
});

example.js:1: WARNING - Property on never defined on Firebase.Query
ref.orderByChild("weight").limitToLast(2).on("child_added", function(snapshot) {

I am assuming from the example they provide that limitToLast() and some or all of the rest of the Query functions should look like Firebase.prototype functions to the compiler, rather than Firebase.Query.prototype?

**Comment by isabo** [comment]
Thanks - my mistake. The documentation clearly lists on(), off() and once() as belonging to Query as well.

When I documented the Query methods, it seemed that the easiest way was to include the query methods in the Firebase class, since Query and Firebase seem somewhat interchangeable. However, that would allow you to make stupid mistakes like add a push() or transaction() call the the end of a query, which makes no sense. I think this could be why the Firebase developers separated the query methods into a different class. They have an overlap (common methods) but they are not the same.

**Comment by dahart** [comment]
Thanks! So yeah, it makes sense that queries and refs are separate. Your update does fix exactly the issue I raised. Turns out the case in my code that led me there was slightly different, and I didn't see the difference until now. I have a call to Firebase.limitToLast(1) that I believe is legit, and the api will default implicitly to ordering by key. So maybe some of the query functions should also cross over into the ref externs?

**Comment by isabo** [comment]
The `orderBy*` methods are indeed available on the regular ref prototype. However, according to the examples in the documentation, the `limitTo*` methods seem to be relevant only for queries, not for refs.
If a `limitTo*` method is used directly on a ref, without a preceding query method, even if it seems to work, wouldn't it usually be more indicative of a probable missing query in the code? If so, wouldn't it be better _not_ to support this undocumented use, and to require you to specify an explicit query such as `orderByKey()`?

**Comment by dahart** [comment]
Yes, I think you're right and its better to be explicit. My code should be
updated, not the externs. Thanks for your help!
